# Generated by Django 3.2.6 on 2021-08-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='partner',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
